name: FirstAC
author: BlebDaPleb
version: '${project.version}'
main: me.blebdapleb.firstac.FirstAC
api-version: 1.17
depend: [ProtocolLib]
permissions:
  anticheat.alerts.view:
    description: Allows users to see anticheat flags/alerts
    default: op